# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 16:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restful', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Danlu_send_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=128, verbose_name='\u53d1\u9001\u4eba')),
                ('receiver', models.CharField(max_length=128, verbose_name='\u63a5\u6536\u4eba')),
                ('send_type', models.CharField(max_length=128, verbose_name='\u53d1\u9001\u5f62\u5f0f')),
                ('send_level', models.CharField(choices=[('info', 'info'), ('warn', 'warn'), ('crit', 'crit')], default='info', max_length=128, verbose_name='\u6d88\u606f\u7ea7\u522b')),
                ('send_content', models.TextField(blank=True, default='', verbose_name='\u6d88\u606f\u5185\u5bb9')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u4e39\u9732\u53d1\u9001\u6d88\u606fapi',
                'verbose_name_plural': '\u4e39\u9732\u53d1\u9001\u6d88\u606fapi',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crteate_time', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u9001\u65f6\u95f4')),
                ('sender', models.CharField(max_length=128, verbose_name='\u53d1\u9001\u4eba')),
                ('receiver', models.CharField(help_text='\u4ee5\u5206\u53f7\u5206\u9694\uff0c\u5982\u679c\u4e0d\u5e26\u90ae\u7bb1\u540e\u7f00\uff0c\u5219\u90ae\u4ef6\u53d1\u9001\u65f6\u9ed8\u8ba4\u4f7f\u7528@dragonest.com', max_length=128, verbose_name='\u63a5\u6536\u4eba')),
                ('type', models.CharField(help_text='\u53ef\u6307\u5b9a\u591a\u79cd\u53d1\u9001\u65b9\u5f0f\uff0c\u4ee5;\u5206\u9694\uff0c\u53ef\u9009\u65b9\u5f0f\u5305\u62ec: wx;email;sms;qyqq;voice;oneapm', max_length=64, verbose_name='\u53d1\u9001\u65b9\u5f0f')),
                ('level', models.CharField(choices=[('info', 'info'), ('warn', 'warn'), ('crit', 'crit')], default='info', help_text='\u6d88\u606f\u7ea7\u522b, \u8bed\u97f3\u901a\u77e5\u8981\u6c42crit\u7ea7\u522b', max_length=8, verbose_name='\u6d88\u606f\u7ea7\u522b')),
                ('title', models.CharField(help_text='\u6807\u9898', max_length=256, verbose_name='\u6807\u9898')),
                ('content', models.TextField(blank=True, default='', verbose_name='\u8be6\u7ec6\u5185\u5bb9')),
                ('log', models.TextField(blank=True, default='', verbose_name='\u53d1\u9001\u65e5\u5fd7')),
            ],
            options={
                'verbose_name': '\u6d88\u606f',
                'verbose_name_plural': '\u6d88\u606f',
            },
        ),
    ]
