# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 01:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restful', '0002_danlu_send_message_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.RemoveField(
            model_name='danlu_send_message',
            name='owner',
        ),
    ]
