# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful', '0003_auto_20170624_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testmesg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
    ]
